version: "3.8"

services:
  mongo:
    container_name: mongo
    image: mongo
    build: ./mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - db-data:/data/db
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - backend
    restart: always
  app:
    container_name: app
    build: ./app
    environment: 
      APP_PORT: ${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - app-data:/opt/armut/app/data
    networks:
      - backend
    restart: always
volumes:
  db-data:
  app-data:
networks:
  backend: